# Generated by Django 3.1.7 on 2021-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210319_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='microbusiness',
        ),
    ]
