# Generated by Django 3.1.7 on 2021-02-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='MicroBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='areas_logo')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MicroBusiness',
                'verbose_name_plural': 'MicroBusinesses',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=60)),
                ('name_contact', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('cel_phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=60)),
                ('web', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypeArticle',
                'verbose_name_plural': 'TypeArticles',
            },
        ),
        migrations.CreateModel(
            name='DocumentsPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('microbusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.microbusiness')),
            ],
            options={
                'verbose_name': 'DocumentPdf',
                'verbose_name_plural': 'DocumentPdfs',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=50)),
                ('cost_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userful_life', models.DateField()),
                ('actual_state', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Seminuevo', 'Seminuevo'), ('Usado', 'Usado'), ('Otros', 'Otros')], max_length=12)),
                ('date_check', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('qr', models.ImageField(blank=True, max_length=255, null=True, upload_to='qrcodes')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('fk_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
                ('fk_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('fk_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
