# Generated by Django 3.1.7 on 2021-02-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentspdf',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='microbusiness',
            name='deleted',
        ),
    ]
