# Generated by Django 3.0.3 on 2020-04-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
