# Generated by Django 3.0.3 on 2020-03-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='fk_category',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
