# Generated by Django 3.1.7 on 2021-02-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210225_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspdf',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microbusiness',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
