# Generated by Django 3.0.3 on 2020-04-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='delete',
        ),
    ]
