# Generated by Django 3.1.7 on 2021-03-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210304_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcomment',
            name='microbusiness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.microbusiness'),
            preserve_default=False,
        ),
    ]
