# Generated by Django 3.0.3 on 2020-03-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20200322_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='fk_brand',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Brand'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='fk_microbusiness',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_microbusiness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.MicroBusiness'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='fk_supplier',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
