# Generated by Django 3.0.3 on 2020-03-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200322_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
        migrations.AlterField(
            model_name='articles',
            name='actual_state',
            field=models.CharField(choices=[('Nuevo_1', 'Nuevo'), ('Semi_nuevo_2', 'Semi_nuevo'), ('Usado_3', 'Usado'), ('Otros_4', 'Otros')], max_length=12),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
