# Generated by Django 3.0.3 on 2020-04-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200413_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='update',
        ),
    ]
