# Generated by Django 3.1.7 on 2021-03-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_allarticles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allarticles',
            options={'verbose_name': 'AllArticle', 'verbose_name_plural': 'AllArticles'},
        ),
    ]
