# Generated by Django 3.0.3 on 2020-03-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200323_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='delete',
        ),
    ]
