# Generated by Django 3.0.3 on 2020-04-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_articles_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
