# Generated by Django 3.1.7 on 2021-04-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210331_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='total_todo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
