# Generated by Django 3.1.7 on 2021-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_articles_total_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='total_todo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
