# Generated by Django 3.0.3 on 2020-04-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_articles_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delete',
        ),
    ]
