# Generated by Django 3.1.7 on 2021-04-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210426_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='total_todo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
