# Generated by Django 3.1.7 on 2021-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210426_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='total_todo',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
