# Generated by Django 3.0.7 on 2020-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200429_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='fk_microbusiness',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ImageField(null=True, upload_to='media/inventory/articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
