# Generated by Django 3.0.7 on 2020-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200612_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='actual_state',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Semi_nuevo', 'Semi_nuevo'), ('Usado', 'Usado'), ('Otros', 'Otros')], max_length=12),
        ),
    ]
