# Generated by Django 3.0.7 on 2020-09-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20200616_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.SmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'quantity',
                'verbose_name_plural': 'quantities',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='fk_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Brand'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fk_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fk_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.quantity'),
        ),
    ]
