# Generated by Django 3.0.7 on 2020-09-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20200922_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.SmallIntegerField(null=True),
        ),
    ]
