# Generated by Django 3.0.7 on 2020-09-22 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20200922_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Quantity'),
        ),
    ]
