# Generated by Django 3.0.7 on 2020-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20200922_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='quantity',
        ),
    ]
