# Generated by Django 3.0.7 on 2021-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_delete_exit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='coust_buy',
            new_name='cost_buy',
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
