# Generated by Django 3.0.7 on 2021-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20210202_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='articles',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
    ]
