# Generated by Django 3.0.7 on 2021-02-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210202_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='qrcode',
            new_name='qr',
        ),
    ]
