# Generated by Django 3.0.7 on 2021-02-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20210202_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
