# Generated by Django 3.0.7 on 2021-02-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20210205_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='articles',
            name='qr',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='qrcodes'),
        ),
    ]
