# Generated by Django 3.0.7 on 2021-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20210207_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Areas')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='actual_state',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Seminuevo', 'Seminuevo'), ('Usado', 'Usado'), ('Otros', 'Otros')], max_length=12),
        ),
    ]
