# Generated by Django 3.0.7 on 2021-02-12 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20210211_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AddField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='area',
            table=None,
        ),
    ]
