# Generated by Django 3.0.7 on 2021-02-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20210212_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.RemoveField(
            model_name='area',
            name='created',
        ),
        migrations.RemoveField(
            model_name='area',
            name='id',
        ),
        migrations.RemoveField(
            model_name='area',
            name='modified',
        ),
        migrations.AddField(
            model_name='area',
            name='Area_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.MicroBusiness'),
            preserve_default=False,
        ),
    ]
