# Generated by Django 3.0.7 on 2021-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20210213_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbusiness',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbusiness',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Areas'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
