# Generated by Django 3.0.7 on 2021-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20210214_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbusiness',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='microbusiness',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='areas_logo'),
        ),
    ]
